Repository hassio-addons/addon-influxdb, pull requests merged in 2021-01, with the labels that each got.

#107 Upgrade add-on base image to 4.0.0
  influxdb/Dockerfile
  influxdb/build.json
Labels: dependencies

#108 Restore add-on Supervisor API access
  influxdb/config.json
Labels: bugfix

#110 ⬆️ Upgrades Chronograf to 1.8.9.1
  influxdb/Dockerfile
Labels: bugfix, dependencies

#101 Clarify user permissions step in documentation
  influxdb/DOCS.md
Labels: documentation

#112 Fix CI badges to show the right status
  README.md
Labels: documentation

#116 Remove obsolete webui from configuration
  influxdb/config.json
Labels: maintenance
