Repository hassio-addons/addon-influxdb, pull requests merged in 2023-03, with the labels that each got.

#271 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  influxdb/Dockerfile
Labels: maintenance

#276 ⬆️ Upgrades Chronograf to 1.10.1
  influxdb/Dockerfile
Labels: dependencies

#277 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  influxdb/.README.j2
  influxdb/DOCS.md
Labels: maintenance

#279 Fix broken URL
  influxdb/DOCS.md
Labels: documentation
