Repository hassio-addons/addon-influxdb, pull requests merged in 2024-01, with the labels that each got.

#314 :fireworks: Updates maintenance/license year to 2024
  LICENSE.md
  README.md
  influxdb/.README.j2
  influxdb/DOCS.md
Labels: maintenance

#304 Fix application of the “reporting” setting
  influxdb/rootfs/etc/cont-init.d/influxdb.sh
Labels: bugfix

#312 ⬆️ Update Chronograf to 1.10.2
  influxdb/Dockerfile
Labels: dependencies
